package com.upnext.notabox.common

object Constants {
    const val NOTE_ID_TO_CREATE_NOTE_SCREEN = "NOTE_ID_TO_CREATE_NOTE_SCREEN"
    const val FOLDER_ID_TO_CREATE_NOTE_SCREEN_IF_IS_CURRENTLY_FOLDER_SELECTED = "FOLDER_ID_TO_CREATE_NOTE_SCREEN_IF_IS_CURRENTLY_FOLDER_SELECTED"
    const val CREATE_NOTE_PARAM_PASSED_TO_CREATE_NOTE_SCREEN = "null_id"
    const val ADD_NOTE_TO_FOLDER_PARAM_PASSED_TO_CREATE_NOTE_SCREEN_IS_MINUS_ONE = -1



}